// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/engine.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_Start_FullMethodName          = "/engine.EngineService/Start"
	EngineService_Stop_FullMethodName           = "/engine.EngineService/Stop"
	EngineService_Status_FullMethodName         = "/engine.EngineService/Status"
	EngineService_Logs_FullMethodName           = "/engine.EngineService/Logs"
	EngineService_SnapshotSave_FullMethodName   = "/engine.EngineService/SnapshotSave"
	EngineService_SnapshotLoad_FullMethodName   = "/engine.EngineService/SnapshotLoad"
	EngineService_SnapshotList_FullMethodName   = "/engine.EngineService/SnapshotList"
	EngineService_SnapshotDelete_FullMethodName = "/engine.EngineService/SnapshotDelete"
	EngineService_Doctor_FullMethodName         = "/engine.EngineService/Doctor"
	EngineService_Reset_FullMethodName          = "/engine.EngineService/Reset"
	EngineService_Ping_FullMethodName           = "/engine.EngineService/Ping"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineServiceClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	SnapshotSave(ctx context.Context, in *SnapshotSaveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	SnapshotLoad(ctx context.Context, in *SnapshotLoadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error)
	SnapshotDelete(ctx context.Context, in *SnapshotDeleteRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Doctor(ctx context.Context, in *DoctorRequest, opts ...grpc.CallOption) (*DoctorResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[0], EngineService_Start_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_StartClient = grpc.ServerStreamingClient[StreamResponse]

func (c *engineServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EngineService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EngineService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[1], EngineService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_LogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *engineServiceClient) SnapshotSave(ctx context.Context, in *SnapshotSaveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[2], EngineService_SnapshotSave_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotSaveRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SnapshotSaveClient = grpc.ServerStreamingClient[StreamResponse]

func (c *engineServiceClient) SnapshotLoad(ctx context.Context, in *SnapshotLoadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[3], EngineService_SnapshotLoad_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotLoadRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SnapshotLoadClient = grpc.ServerStreamingClient[StreamResponse]

func (c *engineServiceClient) SnapshotList(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotListResponse)
	err := c.cc.Invoke(ctx, EngineService_SnapshotList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) SnapshotDelete(ctx context.Context, in *SnapshotDeleteRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EngineService_SnapshotDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Doctor(ctx context.Context, in *DoctorRequest, opts ...grpc.CallOption) (*DoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorResponse)
	err := c.cc.Invoke(ctx, EngineService_Doctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngineService_ServiceDesc.Streams[4], EngineService_Reset_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResetRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_ResetClient = grpc.ServerStreamingClient[StreamResponse]

func (c *engineServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, EngineService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
type EngineServiceServer interface {
	Start(*StartRequest, grpc.ServerStreamingServer[StreamResponse]) error
	Stop(context.Context, *StopRequest) (*StatusResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	SnapshotSave(*SnapshotSaveRequest, grpc.ServerStreamingServer[StreamResponse]) error
	SnapshotLoad(*SnapshotLoadRequest, grpc.ServerStreamingServer[StreamResponse]) error
	SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error)
	SnapshotDelete(context.Context, *SnapshotDeleteRequest) (*StatusResponse, error)
	Doctor(context.Context, *DoctorRequest) (*DoctorResponse, error)
	Reset(*ResetRequest, grpc.ServerStreamingServer[StreamResponse]) error
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) Start(*StartRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedEngineServiceServer) Stop(context.Context, *StopRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedEngineServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEngineServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedEngineServiceServer) SnapshotSave(*SnapshotSaveRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SnapshotSave not implemented")
}
func (UnimplementedEngineServiceServer) SnapshotLoad(*SnapshotLoadRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SnapshotLoad not implemented")
}
func (UnimplementedEngineServiceServer) SnapshotList(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotList not implemented")
}
func (UnimplementedEngineServiceServer) SnapshotDelete(context.Context, *SnapshotDeleteRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotDelete not implemented")
}
func (UnimplementedEngineServiceServer) Doctor(context.Context, *DoctorRequest) (*DoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Doctor not implemented")
}
func (UnimplementedEngineServiceServer) Reset(*ResetRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedEngineServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).Start(m, &grpc.GenericServerStream[StartRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_StartServer = grpc.ServerStreamingServer[StreamResponse]

func _EngineService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_LogsServer = grpc.ServerStreamingServer[LogEntry]

func _EngineService_SnapshotSave_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotSaveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).SnapshotSave(m, &grpc.GenericServerStream[SnapshotSaveRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SnapshotSaveServer = grpc.ServerStreamingServer[StreamResponse]

func _EngineService_SnapshotLoad_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotLoadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).SnapshotLoad(m, &grpc.GenericServerStream[SnapshotLoadRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_SnapshotLoadServer = grpc.ServerStreamingServer[StreamResponse]

func _EngineService_SnapshotList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).SnapshotList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_SnapshotList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).SnapshotList(ctx, req.(*SnapshotListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_SnapshotDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).SnapshotDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_SnapshotDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).SnapshotDelete(ctx, req.(*SnapshotDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Doctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Doctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Doctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Doctor(ctx, req.(*DoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_Reset_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServiceServer).Reset(m, &grpc.GenericServerStream[ResetRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngineService_ResetServer = grpc.ServerStreamingServer[StreamResponse]

func _EngineService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _EngineService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _EngineService_Status_Handler,
		},
		{
			MethodName: "SnapshotList",
			Handler:    _EngineService_SnapshotList_Handler,
		},
		{
			MethodName: "SnapshotDelete",
			Handler:    _EngineService_SnapshotDelete_Handler,
		},
		{
			MethodName: "Doctor",
			Handler:    _EngineService_Doctor_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _EngineService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Start",
			Handler:       _EngineService_Start_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _EngineService_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SnapshotSave",
			Handler:       _EngineService_SnapshotSave_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SnapshotLoad",
			Handler:       _EngineService_SnapshotLoad_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Reset",
			Handler:       _EngineService_Reset_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/engine.proto",
}
