// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/engine.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        int64                  `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *StartRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath        string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Service            string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	GracePeriodSeconds int32                  `protobuf:"varint,3,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *StopRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StopRequest) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Tail          int32                  `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	Since         string                 `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{5}
}

func (x *LogsRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *LogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *LogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Raw           []byte                 `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Services      []*ServiceStatus       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Health        string                 `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ContainerId   string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RestartCount  int32                  `protobuf:"varint,6,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_proto_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceStatus) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ServiceStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ServiceStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_proto_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{9}
}

func (x *StreamResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SnapshotSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IncludeLogs   bool                   `protobuf:"varint,3,opt,name=include_logs,json=includeLogs,proto3" json:"include_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotSaveRequest) Reset() {
	*x = SnapshotSaveRequest{}
	mi := &file_proto_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSaveRequest) ProtoMessage() {}

func (x *SnapshotSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSaveRequest.ProtoReflect.Descriptor instead.
func (*SnapshotSaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotSaveRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SnapshotSaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotSaveRequest) GetIncludeLogs() bool {
	if x != nil {
		return x.IncludeLogs
	}
	return false
}

type SnapshotLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SnapshotPath  string                 `protobuf:"bytes,3,opt,name=snapshot_path,json=snapshotPath,proto3" json:"snapshot_path,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotLoadRequest) Reset() {
	*x = SnapshotLoadRequest{}
	mi := &file_proto_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotLoadRequest) ProtoMessage() {}

func (x *SnapshotLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotLoadRequest.ProtoReflect.Descriptor instead.
func (*SnapshotLoadRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotLoadRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SnapshotLoadRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotLoadRequest) GetSnapshotPath() string {
	if x != nil {
		return x.SnapshotPath
	}
	return ""
}

func (x *SnapshotLoadRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type SnapshotListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotListRequest) Reset() {
	*x = SnapshotListRequest{}
	mi := &file_proto_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotListRequest) ProtoMessage() {}

func (x *SnapshotListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotListRequest.ProtoReflect.Descriptor instead.
func (*SnapshotListRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotListRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

type SnapshotListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotListResponse) Reset() {
	*x = SnapshotListResponse{}
	mi := &file_proto_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotListResponse) ProtoMessage() {}

func (x *SnapshotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotListResponse.ProtoReflect.Descriptor instead.
func (*SnapshotListResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotListResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	HashSha256    string                 `protobuf:"bytes,4,opt,name=hash_sha256,json=hashSha256,proto3" json:"hash_sha256,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{14}
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Snapshot) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Snapshot) GetHashSha256() string {
	if x != nil {
		return x.HashSha256
	}
	return ""
}

func (x *Snapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Snapshot) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type SnapshotDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDeleteRequest) Reset() {
	*x = SnapshotDeleteRequest{}
	mi := &file_proto_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDeleteRequest) ProtoMessage() {}

func (x *SnapshotDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDeleteRequest.ProtoReflect.Descriptor instead.
func (*SnapshotDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotDeleteRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SnapshotDeleteRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type DoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorRequest) Reset() {
	*x = DoctorRequest{}
	mi := &file_proto_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorRequest) ProtoMessage() {}

func (x *DoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorRequest.ProtoReflect.Descriptor instead.
func (*DoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{16}
}

func (x *DoctorRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *DoctorRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type DoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*DiagnosticIssue     `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Suggestions   []string               `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_proto_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{17}
}

func (x *DoctorResponse) GetIssues() []*DiagnosticIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *DoctorResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type DiagnosticIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticIssue) Reset() {
	*x = DiagnosticIssue{}
	mi := &file_proto_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticIssue) ProtoMessage() {}

func (x *DiagnosticIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticIssue.ProtoReflect.Descriptor instead.
func (*DiagnosticIssue) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{18}
}

func (x *DiagnosticIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DiagnosticIssue) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DiagnosticIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiagnosticIssue) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{19}
}

func (x *ResetRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *ResetRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type SecretSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSetRequest) Reset() {
	*x = SecretSetRequest{}
	mi := &file_proto_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSetRequest) ProtoMessage() {}

func (x *SecretSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSetRequest.ProtoReflect.Descriptor instead.
func (*SecretSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{20}
}

func (x *SecretSetRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SecretSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SecretGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGetRequest) Reset() {
	*x = SecretGetRequest{}
	mi := &file_proto_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGetRequest) ProtoMessage() {}

func (x *SecretGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGetRequest.ProtoReflect.Descriptor instead.
func (*SecretGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{21}
}

func (x *SecretGetRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SecretGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SecretGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGetResponse) Reset() {
	*x = SecretGetResponse{}
	mi := &file_proto_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGetResponse) ProtoMessage() {}

func (x *SecretGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGetResponse.ProtoReflect.Descriptor instead.
func (*SecretGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{22}
}

func (x *SecretGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SecretListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListRequest) Reset() {
	*x = SecretListRequest{}
	mi := &file_proto_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListRequest) ProtoMessage() {}

func (x *SecretListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListRequest.ProtoReflect.Descriptor instead.
func (*SecretListRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{23}
}

func (x *SecretListRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

type SecretListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretEntry         `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListResponse) Reset() {
	*x = SecretListResponse{}
	mi := &file_proto_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListResponse) ProtoMessage() {}

func (x *SecretListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListResponse.ProtoReflect.Descriptor instead.
func (*SecretListResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{24}
}

func (x *SecretListResponse) GetSecrets() []*SecretEntry {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *SecretListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SecretEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretEntry) Reset() {
	*x = SecretEntry{}
	mi := &file_proto_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretEntry) ProtoMessage() {}

func (x *SecretEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretEntry.ProtoReflect.Descriptor instead.
func (*SecretEntry) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{25}
}

func (x *SecretEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SecretEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SecretEntry) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SecretDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDeleteRequest) Reset() {
	*x = SecretDeleteRequest{}
	mi := &file_proto_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteRequest) ProtoMessage() {}

func (x *SecretDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDeleteRequest.ProtoReflect.Descriptor instead.
func (*SecretDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{26}
}

func (x *SecretDeleteRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SecretDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SecretRotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRotateRequest) Reset() {
	*x = SecretRotateRequest{}
	mi := &file_proto_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRotateRequest) ProtoMessage() {}

func (x *SecretRotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRotateRequest.ProtoReflect.Descriptor instead.
func (*SecretRotateRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{27}
}

func (x *SecretRotateRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *SecretRotateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_engine_proto protoreflect.FileDescriptor

const file_proto_engine_proto_rawDesc = "" +
	"\n" +
	"\x12proto/engine.proto\x12\x06engine\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x03R\x06uptime\"G\n" +
	"\fStartRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"|\n" +
	"\vStopRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x120\n" +
	"\x14grace_period_seconds\x18\x03 \x01(\x05R\x12gracePeriodSeconds\"2\n" +
	"\rStatusRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\"\x8c\x01\n" +
	"\vLogsRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\x05R\x04tail\x12\x14\n" +
	"\x05since\x18\x04 \x01(\tR\x05since\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"\x84\x01\n" +
	"\bLogEntry\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\fR\x03raw\"q\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x121\n" +
	"\bservices\x18\x02 \x03(\v2\x15.engine.ServiceStatusR\bservices\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xaf\x01\n" +
	"\rServiceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\x03 \x01(\tR\x06health\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12#\n" +
	"\rrestart_count\x18\x06 \x01(\x05R\frestartCount\"l\n" +
	"\x0eStreamResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"o\n" +
	"\x13SnapshotSaveRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\finclude_logs\x18\x03 \x01(\bR\vincludeLogs\"\x94\x01\n" +
	"\x13SnapshotLoadRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12#\n" +
	"\rsnapshot_path\x18\x03 \x01(\tR\fsnapshotPath\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"8\n" +
	"\x13SnapshotListRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\"F\n" +
	"\x14SnapshotListResponse\x12.\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x10.engine.SnapshotR\tsnapshots\"\xa9\x01\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vhash_sha256\x18\x04 \x01(\tR\n" +
	"hashSha256\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"[\n" +
	"\x15SnapshotDeleteRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"L\n" +
	"\rDoctorRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"c\n" +
	"\x0eDoctorResponse\x12/\n" +
	"\x06issues\x18\x01 \x03(\v2\x17.engine.DiagnosticIssueR\x06issues\x12 \n" +
	"\vsuggestions\x18\x02 \x03(\tR\vsuggestions\"{\n" +
	"\x0fDiagnosticIssue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"G\n" +
	"\fResetRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"_\n" +
	"\x10SecretSetRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"I\n" +
	"\x10SecretGetRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"S\n" +
	"\x11SecretGetResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"6\n" +
	"\x11SecretListRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\"Y\n" +
	"\x12SecretListResponse\x12-\n" +
	"\asecrets\x18\x01 \x03(\v2\x13.engine.SecretEntryR\asecrets\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"w\n" +
	"\vSecretEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"L\n" +
	"\x13SecretDeleteRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"L\n" +
	"\x13SecretRotateRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xfe\a\n" +
	"\rEngineService\x127\n" +
	"\x05Start\x12\x14.engine.StartRequest\x1a\x16.engine.StreamResponse0\x01\x123\n" +
	"\x04Stop\x12\x13.engine.StopRequest\x1a\x16.engine.StatusResponse\x127\n" +
	"\x06Status\x12\x15.engine.StatusRequest\x1a\x16.engine.StatusResponse\x12/\n" +
	"\x04Logs\x12\x13.engine.LogsRequest\x1a\x10.engine.LogEntry0\x01\x12E\n" +
	"\fSnapshotSave\x12\x1b.engine.SnapshotSaveRequest\x1a\x16.engine.StreamResponse0\x01\x12E\n" +
	"\fSnapshotLoad\x12\x1b.engine.SnapshotLoadRequest\x1a\x16.engine.StreamResponse0\x01\x12I\n" +
	"\fSnapshotList\x12\x1b.engine.SnapshotListRequest\x1a\x1c.engine.SnapshotListResponse\x12G\n" +
	"\x0eSnapshotDelete\x12\x1d.engine.SnapshotDeleteRequest\x1a\x16.engine.StatusResponse\x127\n" +
	"\x06Doctor\x12\x15.engine.DoctorRequest\x1a\x16.engine.DoctorResponse\x127\n" +
	"\x05Reset\x12\x14.engine.ResetRequest\x1a\x16.engine.StreamResponse0\x01\x121\n" +
	"\x04Ping\x12\x13.engine.PingRequest\x1a\x14.engine.PingResponse\x12=\n" +
	"\tSecretSet\x12\x18.engine.SecretSetRequest\x1a\x16.engine.StatusResponse\x12@\n" +
	"\tSecretGet\x12\x18.engine.SecretGetRequest\x1a\x19.engine.SecretGetResponse\x12C\n" +
	"\n" +
	"SecretList\x12\x19.engine.SecretListRequest\x1a\x1a.engine.SecretListResponse\x12C\n" +
	"\fSecretDelete\x12\x1b.engine.SecretDeleteRequest\x1a\x16.engine.StatusResponse\x12C\n" +
	"\fSecretRotate\x12\x1b.engine.SecretRotateRequest\x1a\x16.engine.StatusResponseB4Z2github.com/devboxos/devboxos/engine/proto;enginepbb\x06proto3"

var (
	file_proto_engine_proto_rawDescOnce sync.Once
	file_proto_engine_proto_rawDescData []byte
)

func file_proto_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)))
	})
	return file_proto_engine_proto_rawDescData
}

var file_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_engine_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: engine.PingRequest
	(*PingResponse)(nil),          // 1: engine.PingResponse
	(*StartRequest)(nil),          // 2: engine.StartRequest
	(*StopRequest)(nil),           // 3: engine.StopRequest
	(*StatusRequest)(nil),         // 4: engine.StatusRequest
	(*LogsRequest)(nil),           // 5: engine.LogsRequest
	(*LogEntry)(nil),              // 6: engine.LogEntry
	(*StatusResponse)(nil),        // 7: engine.StatusResponse
	(*ServiceStatus)(nil),         // 8: engine.ServiceStatus
	(*StreamResponse)(nil),        // 9: engine.StreamResponse
	(*SnapshotSaveRequest)(nil),   // 10: engine.SnapshotSaveRequest
	(*SnapshotLoadRequest)(nil),   // 11: engine.SnapshotLoadRequest
	(*SnapshotListRequest)(nil),   // 12: engine.SnapshotListRequest
	(*SnapshotListResponse)(nil),  // 13: engine.SnapshotListResponse
	(*Snapshot)(nil),              // 14: engine.Snapshot
	(*SnapshotDeleteRequest)(nil), // 15: engine.SnapshotDeleteRequest
	(*DoctorRequest)(nil),         // 16: engine.DoctorRequest
	(*DoctorResponse)(nil),        // 17: engine.DoctorResponse
	(*DiagnosticIssue)(nil),       // 18: engine.DiagnosticIssue
	(*ResetRequest)(nil),          // 19: engine.ResetRequest
	(*SecretSetRequest)(nil),      // 20: engine.SecretSetRequest
	(*SecretGetRequest)(nil),      // 21: engine.SecretGetRequest
	(*SecretGetResponse)(nil),     // 22: engine.SecretGetResponse
	(*SecretListRequest)(nil),     // 23: engine.SecretListRequest
	(*SecretListResponse)(nil),    // 24: engine.SecretListResponse
	(*SecretEntry)(nil),           // 25: engine.SecretEntry
	(*SecretDeleteRequest)(nil),   // 26: engine.SecretDeleteRequest
	(*SecretRotateRequest)(nil),   // 27: engine.SecretRotateRequest
}
var file_proto_engine_proto_depIdxs = []int32{
	8,  // 0: engine.StatusResponse.services:type_name -> engine.ServiceStatus
	14, // 1: engine.SnapshotListResponse.snapshots:type_name -> engine.Snapshot
	18, // 2: engine.DoctorResponse.issues:type_name -> engine.DiagnosticIssue
	25, // 3: engine.SecretListResponse.secrets:type_name -> engine.SecretEntry
	2,  // 4: engine.EngineService.Start:input_type -> engine.StartRequest
	3,  // 5: engine.EngineService.Stop:input_type -> engine.StopRequest
	4,  // 6: engine.EngineService.Status:input_type -> engine.StatusRequest
	5,  // 7: engine.EngineService.Logs:input_type -> engine.LogsRequest
	10, // 8: engine.EngineService.SnapshotSave:input_type -> engine.SnapshotSaveRequest
	11, // 9: engine.EngineService.SnapshotLoad:input_type -> engine.SnapshotLoadRequest
	12, // 10: engine.EngineService.SnapshotList:input_type -> engine.SnapshotListRequest
	15, // 11: engine.EngineService.SnapshotDelete:input_type -> engine.SnapshotDeleteRequest
	16, // 12: engine.EngineService.Doctor:input_type -> engine.DoctorRequest
	19, // 13: engine.EngineService.Reset:input_type -> engine.ResetRequest
	0,  // 14: engine.EngineService.Ping:input_type -> engine.PingRequest
	20, // 15: engine.EngineService.SecretSet:input_type -> engine.SecretSetRequest
	21, // 16: engine.EngineService.SecretGet:input_type -> engine.SecretGetRequest
	23, // 17: engine.EngineService.SecretList:input_type -> engine.SecretListRequest
	26, // 18: engine.EngineService.SecretDelete:input_type -> engine.SecretDeleteRequest
	27, // 19: engine.EngineService.SecretRotate:input_type -> engine.SecretRotateRequest
	9,  // 20: engine.EngineService.Start:output_type -> engine.StreamResponse
	7,  // 21: engine.EngineService.Stop:output_type -> engine.StatusResponse
	7,  // 22: engine.EngineService.Status:output_type -> engine.StatusResponse
	6,  // 23: engine.EngineService.Logs:output_type -> engine.LogEntry
	9,  // 24: engine.EngineService.SnapshotSave:output_type -> engine.StreamResponse
	9,  // 25: engine.EngineService.SnapshotLoad:output_type -> engine.StreamResponse
	13, // 26: engine.EngineService.SnapshotList:output_type -> engine.SnapshotListResponse
	7,  // 27: engine.EngineService.SnapshotDelete:output_type -> engine.StatusResponse
	17, // 28: engine.EngineService.Doctor:output_type -> engine.DoctorResponse
	9,  // 29: engine.EngineService.Reset:output_type -> engine.StreamResponse
	1,  // 30: engine.EngineService.Ping:output_type -> engine.PingResponse
	7,  // 31: engine.EngineService.SecretSet:output_type -> engine.StatusResponse
	22, // 32: engine.EngineService.SecretGet:output_type -> engine.SecretGetResponse
	24, // 33: engine.EngineService.SecretList:output_type -> engine.SecretListResponse
	7,  // 34: engine.EngineService.SecretDelete:output_type -> engine.StatusResponse
	7,  // 35: engine.EngineService.SecretRotate:output_type -> engine.StatusResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_engine_proto_init() }
func file_proto_engine_proto_init() {
	if File_proto_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_proto_depIdxs,
		MessageInfos:      file_proto_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_proto = out.File
	file_proto_engine_proto_goTypes = nil
	file_proto_engine_proto_depIdxs = nil
}
